#Run optimization with:
# uv run run_optimization.py --config_file example_config_optimization.yaml --other_optional_parameters
# or
# python run_optimization.py --config_file example_config_optimization.yaml --other_optional_parameters

############ System parameters
system: "Shastry_Sutherland"  #Square_Heisenberg / Shastry_Sutherland
L: 4
J: [0.8, 1]
#sign_rule: [0,0] #Square_Heisenberg
#patching: 1 #Square_Heisenberg

########### Network parameters
network: "ConvNext" #ResCNN/ViT2D/ConvNext
#ConvNext args
n_blocks: 1
features: 12
expansion_factor: 2
net_type: "Vanilla" #Vanilla/NoPatching
kernel_width: 2
downsample_factor: 2
final_features: 12
init_kernel_width: 1 #dummy for net_type = Vanilla

########### Optimization Parameters
samples_per_rank: 1024
n_chains_per_rank: 512
discard_fraction: 0
# iters: [2500,2500,2500,2500]
# lr: [1e-2,1e-2,1e-2,1e-2]
# lr_factor: [0.5,0.5,0.5,0.5]
# diag_shift: [1e-2,1e-2,1e-2,1e-2]
# diag_shift_factor: [1e-4,1e-4,1e-4,1e-4]
iters: 10
lr: 1e-2
lr_factor: 0.5
diag_shift: 1e-2
diag_shift_factor: 1e-2
r: 1e-6
chunk_size: 512
save_every: 10
symmetries: 0
symmetry_ramping: 0
post_iters: 5
sweep_factor: 1

########## Other parameters
save_base: ''
save_num: 0
time_it: 0
show_progress: 1
double_precision: 1









